### ISSUE TITLE
installing und ubuntu 16.04 not working

### ISSUE THREAD

**Issue by olissongs** [rolfkleef/zim-plantuml#2]
Hi,

i did installation like in your readme but no plntuml plugin is shown working on zim 0.65
any hints?

regards
Oliver

**Comment by olissongs** [comment]
Files are in there:
~/.local/share/zim/plugins/ 
.
├── plugins
│   ├── IconTags.py
│   ├── my-style.plantuml
│   ├── plantumleditor.py
│   ├── plantuml.jar
│   ├── tree2mindmap.py
│   └── tree2mindmap.pyc

but it seems that nothing is working

**Comment by olissongs** [comment]
ok no everything is fine, i had an downloading problem the files directly via browser. After downloading zip and extracting it in the documented place, restart an voila.
i like this plugin very much-

**Comment by rolfkleef** [comment]
thanks, glad you solved yourself it while I was away :-)
