### ISSUE TITLE
please make it work in zim windows

### ISSUE THREAD

**Issue by xvusrmqj** [rolfkleef/zim-plantuml#3]
I use windows not ubuntu. please make it work in zim windows.

**Comment by rolfkleef** [comment]
I don't use Windows so I won't make it work in Windows, but if anyone wants to contribute...

**Comment by adimiti** [comment]
Change line 22 ```dotcmd = ('plantuml')``` to ```dotcmd = (r'java -jar drive:\pathto\plantuml.jar')```.

**Comment by rolfkleef** [comment]
Closing this, a newer version for more recent Zim versions [is available here](https://gitlab.com/Voyvode/zim-umldiagrameditor)
