### ISSUE TITLE
Not working in Debian 9

### ISSUE THREAD

**Issue by carugnom** [rolfkleef/zim-plantuml#4]
I've followed the instructions (for Ubuntu 16.04)
The plugin is able to be activated, but when I insert a PlantUML example, only a image 'empty' is shown.
Is there any other dependency needed ?

**Comment by rolfkleef** [comment]
I'm not aware of other dependencies, but maybe there are differences between Debian and Ubuntu here.

I've just adapted the [Ditaa plugin](http://zim-wiki.org/manual/Plugins/Ditaa_Editor.html) to use PlantUML, does that plugin work for you?

Does running `plantuml <file>.pu` for a file containing PlantUML source produce a PNG image of that?

**Comment by rolfkleef** [comment]
I've added a link to [a newer version](https://gitlab.com/Voyvode/zim-umldiagrameditor) that hopefully works for you too, and I'm archiving this repository.
