### ISSUE TITLE
Not working with zim 0.72

### ISSUE THREAD

**Issue by caiofior** [rolfkleef/zim-plantuml#5]
It does not work with 0.72 version, if I go back to 0.61 it works again

**Comment by caiofior** [comment]
This project script wors also with zim 072

https://gitlab.com/Voyvode/zim-umldiagrameditor/-/blob/master/umldiagrameditor.py

**Comment by rolfkleef** [comment]
Great you found a newer version! I've added it to the README and will archive this repo.
